name: Build Source

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: "Build Source"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable  
      - name: Install xcpretty
        run: bundle instal
      - name: Build
        run: |
          set -o pipefail && \
          xcodebuild -scheme EasyFirebaseSwift \
          build \
          -destination "name=iPhone 12" \
          | bundle exec xcpretty
