name: Test Source

on: push

jobs:
  test:
    name: "Test Source"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable      
      - name: Test
        run: swift test
